tap "olets/tap"
tap "modem-dev/tap"

brew "chezmoi"
brew "ghq"
brew "peco"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "fd"
brew "olets/tap/zsh-abbr@6"
brew "zsh-autosuggestions"
brew "gh"
brew "mise"
brew "herdr"
brew "fzf"
brew "modem-dev/tap/hunk"

cask "codex"
cask "karabiner-elements"
cask "rancher"
cask "slack"
cask "wezterm"
cask "font-jetbrains-mono"
cask "font-udev-gothic-nf"
cask "font-commit-mono"
