tap "olets/tap"

brew "chezmoi"
brew "ghq"
brew "peco"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "fd"
brew "olets/tap/zsh-abbr@6"
brew "zsh-autosuggestions"
brew "gh"
brew "mise"
brew "herdr"
brew "bun"

cask "codex"
cask "karabiner-elements"
cask "obsidian"
cask "rancher"
cask "slack"
cask "wezterm"
cask "font-jetbrains-mono"
cask "font-ibm-plex-sans-jp"
cask "font-commit-mono"
