#!/bin/bash

CONTAINER_NAME="php-container"

# Get current working directory path 🗂
WORK_DIR=$(pwd)

# Check if container exists 🔍
if ! docker ps -a | grep -q $CONTAINER_NAME; then
    echo "✨ Creating PHP container..."
    docker run -d --name $CONTAINER_NAME \
        -v /Users:/Users \
        -v "${HOME}/.composer:/root/.composer" \
        php:8.4-rc-cli tail -f /dev/null
fi

# Start container if not running 🚀
if ! docker ps | grep -q $CONTAINER_NAME; then
    echo "🔌 Starting PHP container..."
    docker start $CONTAINER_NAME
fi

# Execute Composer command 🎼
docker exec -w "$WORK_DIR" -i $CONTAINER_NAME composer "$@"
