#!/bin/bash

CONTAINER_NAME="php-container"

# Get current working directory path 🗂
WORK_DIR=$(pwd)

# Check if container exists 🔍
if ! docker ps -a | grep -q $CONTAINER_NAME; then
    echo "✨ Creating PHP container..."
    docker run -d --name $CONTAINER_NAME \
        -v /Users:/Users \
        -v "${HOME}/.composer:/root/.composer" \
        php:8.4-rc-cli tail -f /dev/null

    echo "🎼 Installing Composer..."
    docker exec -i $CONTAINER_NAME sh -c 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer'
fi

# Start container if not running 🚀
if ! docker ps | grep -q $CONTAINER_NAME; then
    echo "🔌 Starting PHP container..."
    docker start $CONTAINER_NAME
fi

# Execute command 🎯
docker exec -w "$WORK_DIR" -i $CONTAINER_NAME php "$@"
