tap "olets/tap"
tap "datadog-labs/pack"

brew "chezmoi"
brew "ghq"
brew "peco"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "fd"
brew "olets/tap/zsh-abbr@6"
brew "datadog-labs/pack/pup"
brew "zsh-autosuggestions"
brew "gh"
brew "mise"
brew "herdr"
brew "bun"
brew "dnsmasq"
brew "awscli"
cask "session-manager-plugin"

{{ if .install.beekeeper_studio -}}
cask "beekeeper-studio"
{{ end -}}
{{ if .install.brave_browser -}}
cask "brave-browser"
{{ end -}}
{{ if .install.codex -}}
cask "codex"
{{ end -}}
{{ if .install.coteditor -}}
cask "coteditor"
{{ end -}}
{{ if .install.karabiner_elements -}}
cask "karabiner-elements"
{{ end -}}
{{ if .install.obsidian -}}
cask "obsidian"
{{ end -}}
{{ if .install.rancher -}}
cask "rancher"
{{ end -}}
{{ if .install.raycast -}}
cask "raycast"
{{ end -}}
{{ if .install.slack -}}
cask "slack"
{{ end -}}
{{ if .install.wezterm -}}
cask "wezterm"
{{ end -}}
{{ if .install.wispr_flow -}}
cask "wispr-flow"
{{ end -}}
{{ if .install.font_google_sans_code -}}
cask "font-google-sans-code"
{{ end -}}
{{ if .install.font_biz_udgothic -}}
cask "font-biz-udgothic"
{{ end -}}
